# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
# - task: NuGetToolInstaller@0

# - task: NuGetCommand@2
#   inputs:
#     restoreSolution: '$(solution)'

# - task: VSBuild@1
#   inputs:
#     solution: '$(solution)'
#     msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="$(build.artifactStagingDirectory)\WebApp.zip" /p:DeployIisAppPath="Default Web Site"'
#     platform: '$(buildPlatform)'
#     configuration: '$(buildConfiguration)'

# - task: VSTest@2
#   inputs:
#     platform: '$(buildPlatform)'
#     configuration: '$(buildConfiguration)'
- bash: |
    mkdir ./build
    mkdir ./build/nspclient
    mkdir ./build/nspserver
  displayName: Create build directory
  workingDirectory: './'

- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: './src/NSmartProxy.ServerHost/NSmartProxy.ServerHost.csproj'
    arguments: ' --output ./build/nspserver'

- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: './src/NSmartProxy.ClientRouter/NSmartProxy.ClientRouter.csproj'
    arguments: ' --output ./build/nspclient'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      docker login -u $(dhName) -p $(dhPwd)
      docker build . -t nspserver -f Dockerfile
      docker tag nspserver tmoonlight/nspserver
      docker push tmoonlight/nspserver
    workingDirectory: './build/nspserver'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      docker login -u $(dhName) -p $(dhPwd)
      docker build . -t nspclient -f Dockerfile
      docker tag nspclient tmoonlight/nspclient
      docker push tmoonlight/nspclient
    workingDirectory: './build/nspclient'